server:
  port: 8081
#单机版
#spring:
#  rabbitmq:
#    addresses: 127.0.0.1
#    port: 5672
#    username: user1
#    password: user1
#    virtual-host: myVirtualHost

#集群版
spring:
  rabbitmq:
    addresses: 192.168.1.80:5672,192.168.1.86:5672,192.168.1.87:5672
    username: user1
    password: user1
    virtual-host: myVirtualHost
